spring.application.name=v1
spring.datasource.url=${DB_URL:jdbc:h2:file:./data/budgetbite;AUTO_SERVER=TRUE}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.thymeleaf.cache=false
spring.messages.basename=messages
